agenda
org-makefile

In Makefiles, a phony target is a special type of target that does not represent an actual file to be built. Instead, it serves as a label for a set of commands you want to execute. Using .PHONY is a crucial best practice to make your build system robust and reliable .

🤔 Why You Need Phony Targets

There are two primary reasons to declare a target as phony:

1. To Avoid File Conflicts: By default, make assumes a target is a file. If a file with the same name as your target (e.g., a file called clean) exists in the directory, make will see that the file is present and has no prerequisites. It will then decide the target is "up to date" and will not run the associated commands . Declaring the target as phony tells make to ignore the existence of any same-named file and always execute the commands .

2. To Improve Performance: Because phony targets do not correspond to files, make can skip the implicit rule search for them. This can lead to a slight performance improvement, which is beneficial for complex build systems .

📝 How to Use .PHONY

You declare a target as phony by placing a special line in your Makefile. The standard syntax adds the target as a prerequisite to the special .PHONY target .

# Declaration: tell make these targets are phony
.PHONY: clean all test install

# A target to build all programs
all: prog1 prog2

# A target to clean up build artifacts
clean:
    rm -rf *.o myapp

# A target to run tests
test:
    go test ./...


You can declare multiple phony targets on a single line, as shown above .

🛠️ Common Use Cases for Phony Targets

Phony targets are ideal for any action that doesn't produce an output file with the same name as the target. Here are the most common examples:

• all: This is often the first target and used as the default goal. It typically builds all the components of your project .

• clean: Used to remove all files generated by the build process (like object files or binaries) .

• test or check: Used to run the test suite for your project .

• install: Used to copy the built program and other necessary files to their system-wide directories .

• help: Displays available targets and their purposes .

Phony targets can also have prerequisites and be combined to create more complex operations . For example, a rebuild target might depend on clean and all.

.PHONY: rebuild all clean

# This will run the 'clean' target and then the 'all' target
rebuild: clean all

all: myapp

clean:
    rm -f myapp


💡 Key Practices and a Note on Dependencies

• Always Declare Non-File Targets: For any target that does not create a file with the target's name, declare it with .PHONY .

• Place Declarations Early: It's good practice to place your .PHONY declarations near the top of the Makefile, after variable definitions .

• Dependencies on Real Files: A phony target can depend on a real file. In this case, the phony target's commands will only run if the real file is newer than its prerequisites. For example, a deploy target might depend on the myapp binary; make deploy would only run if myapp is newer than the files it was built from .

In summary, using .PHONY is essential for defining utility targets like clean or all reliably. It ensures your Makefile commands execute correctly regardless of the files in your directory and can make your builds slightly faster .

;;elc

(file-size "test.elc")

;; 加载编译后的文件测试
(load "test.elc")
;; 设置 Org 代码块显示样式
(custom-set-faces
 '(org-block ((t (:background "#f0fff0" :extend t))))
 '(org-block-begin-line ((t (:underline "#90ee90" :background "#e0ffe0"))))
 '(org-block-end-line ((t (:overline "#90ee90" :background "#e0ffe0")))))



;; 开启详细编译模式
(setq byte-compile-verbose t)
(setq byte-compile-debug t)

;; 重新编译查看详细输出

7. 编码设置：在渲染时显式设置buffer编码
4. 空值检查：在所有可能为nil的值前添加了安全检查






1. 编码修复：在文件开头添加了UTF-8编码声明

2. API密钥检查：增强了检查逻辑，处理更多无效密钥情况

3. 错误处理：改进了API响应验证和错误处理

4. 空值检查：在所有可能为nil的值前添加了安全检查

5. HTTPS支持：将API请求从HTTP改为HTTPS

6. 数据验证：增强了数据处理的健壮性
;; -*- coding: utf-8; -*-

;; Fix the weather--filter-by-time-range function
(defun weather--filter-by-time-range (hourly-data days-back days-forward)
  "Filter data by time range"
  (let* ((now (float-time))
         (min-time (- now (* days-back 24 3600)))
         (max-time (+ now (* days-forward 24 3600))))
    (cl-remove-if-not 
     (lambda (hour)
       (let ((dt (plist-get hour :dt)))
         (and dt (>= dt min-time) (<= dt max-time))))
     hourly-data)))

;; Fix the weather-process-data function to handle errors properly
(defun weather-process-data (city data)
  "Process and store weather data for a city"
  (condition-case err
      (progn
        ;; 检查API响应是否包含错误
        (when (and (listp data) (alist-get 'message data))
          (error "API错误: %s" (alist-get 'message data)))
        
        (let* ((city-info (gethash city weather-city-data))
               (existing-hourly (or (plist-get city-info :hourly) '()))
               (api-list (alist-get 'list data))
               (new-hourly (if (and api-list (listp api-list))
                               (mapcar #'weather--create-plist api-list)
                             (error "无效的API响应数据: 缺少list字段")))
               (all-hourly (append existing-hourly new-hourly))
               (filtered-hourly (weather--filter-by-time-range all-hourly 1 5)))
          
          ;; 排序和去重
          (setq filtered-hourly (cl-sort filtered-hourly #'< 
                                        :key (lambda (x) (or (plist-get x :dt) 0))))
          (setq filtered-hourly (cl-remove-duplicates filtered-hourly 
                                                     :test (lambda (a b) 
                                                            (= (or (plist-get a :dt) 0) 
                                                               (or (plist-get b :dt) 0)))))
          
          ;; 分组为每日数据
          (let ((daily-data (weather--group-by-date filtered-hourly)))
            (puthash city `(:city ,city 
                           :hourly ,filtered-hourly 
                           :daily ,daily-data
                           :last-update ,(current-time))
                     weather-city-data))))
    
    (error
     (let ((error-msg (format "%s: 数据处理失败 - %s" city (error-message-string err))))
       (push error-msg weather-error-messages)
       (message "处理 %s 天气数据时出错: %s" city (error-message-string err))))))

;; Fix the weather-start-request function to properly handle errors
(defun weather-start-request (city)
  "Start a weather request for a specific city"
  (weather-check-api-key)
  (condition-case err
      (progn
        (cl-incf weather-active-requests)
        (let ((url (format "https://api.openweathermap.org/data/2.5/forecast?q=%s&appid=%s&units=metric&lang=zh_cn"
                          (url-hexify-string city)
                          openweather-api-key)))
          (url-retrieve url 'weather-api-callback (list city))))
    (error
     (message "启动 %s 天气请求失败: %s" city (error-message-string err))
     (cl-decf weather-active-requests)
     (push (format "%s: 请求失败 - %s" city (error-message-string err)) weather-error-messages))))

;; Fix function to get all unique dates
(defun weather--get-all-dates ()
  "Get all unique dates from weather data"
  (let ((dates '()))
    (maphash (lambda (_ city-data)
               (let ((daily-data (plist-get city-data :daily)))
                 (when (hash-table-p daily-data)
                   (maphash (lambda (date _) 
                              (push date dates))
                            daily-data))))
             weather-city-data)
    (cl-sort (cl-remove-duplicates dates :test 'string=) 'string<)))

;; Format temperature with color coding
(defun weather--format-temperature (temp)
  "Format temperature with color coding"
  (when temp
    (let ((formatted (format "%.1f°C" temp)))
      (cond ((> temp 30) (propertize formatted 'face '(:foreground "red" :weight bold)))
            ((< temp 10) (propertize formatted 'face '(:foreground "blue" :weight bold)))
            (t (propertize formatted 'face '(:foreground "dark green")))))))

;; Format precipitation percentage
(defun weather--format-pop (pop-percent highlight)
  "Format precipitation percentage with highlighting"
  (when pop-percent
    (let ((formatted (format "%d%%" pop-percent)))
      (if (and highlight (>= pop-percent rain-threshold))
          (propertize formatted 'face '(:background "light coral" :weight bold))
        formatted))))

;; Enhanced API key check
(defun weather-check-api-key ()
  "Check if API key is properly set"
  (when (or (null openweather-api-key)
            (string= openweather-api-key "YOUR_API_KEY")
            (string= openweather-api-key "YOUR_OPENWEATHER_API_KEY"))
    (error "请先设置OpenWeatherMap API密钥：M-x set-variable openweather-api-key")))

;; Define OpenWeatherMap API key variable
(defvar openweather-api-key nil
  "OpenWeatherMap API key")

;; Try to get API key from environment variable
(when (and (not openweather-api-key) (getenv "WEATHER"))
  (setq openweather-api-key (getenv "WEATHER")))

;; Define list of cities to monitor weather for
(defvar weather-cities '("Beijing" "Shanghai" "Guangzhou" "Shenzhen")
  "List of cities to display weather for")

;; Other variable definitions remain the same...
(defvar weather-refresh-interval 3600
  "Weather refresh interval in seconds")

(defvar rain-threshold 30
  "Rain highlight threshold (rain probability percentage)")

(defvar weather-buffer-name "城市天气"
  "Weather report buffer name")

(defvar weather-active-requests 0
  "Number of currently active requests")

(defvar weather-city-data (make-hash-table :test 'equal)
  "Storage for city weather data")

(defvar weather-error-messages nil
  "Storage for error messages")

;;; ======================
;;; Enhanced utility functions
;;; ======================

(defun weather--format-time (timestamp &optional format)
  "Format timestamp to readable string"
  (when timestamp
    (format-time-string (or format "%Y-%m-%d %H:%M") (seconds-to-time timestamp))))

(defun weather--create-plist (item)
  "Create property list from API data item"
  (when item
    (let ((dt (alist-get 'dt item))
          (main (alist-get 'main item))
          (weather-vec (alist-get 'weather item))
          (pop (or (alist-get 'pop item) 0))
          (rain (or (alist-get 'rain item) 0))
          (wind (alist-get 'wind item)))
      
      (let ((weather (cond
                      ((vectorp weather-vec) (aref weather-vec 0))
                      ((consp weather-vec) (car weather-vec))
                      (t nil))))
        `(:dt ,dt
          :temp ,(when main (alist-get 'temp main))
          :feels_like ,(when main (alist-get 'feels_like main))
          :humidity ,(when main (alist-get 'humidity main))
          :pressure ,(when main (alist-get 'pressure main))
          :description ,(when weather (alist-get 'description weather))
          :icon ,(when weather (alist-get 'icon weather))
          :pop ,pop
          :rain ,(if (consp rain) (alist-get '3h rain) rain)
          :wind_speed ,(when wind (alist-get 'speed wind)))))))

(defun weather--group-by-date (hourly-data)
  "Group hourly data by date"
  (let ((daily-table (make-hash-table :test 'equal)))
    (dolist (hour hourly-data)
      (when (plist-get hour :dt)
        (let ((date (weather--format-time (plist-get hour :dt) "%Y-%m-%d")))
          (when date
            (push hour (gethash date daily-table '()))))))
    daily-table))

(defun weather--calculate-daily-stats (hours)
  "Calculate daily statistics from hourly data"
  (when hours
    (let ((valid-hours (cl-remove-if-not (lambda (h) (plist-get h :temp)) hours))
          (temps (mapcar (lambda (h) (plist-get h :temp)) hours))
          (pops (mapcar (lambda (h) (or (plist-get h :pop) 0)) hours))
          (rains (mapcar (lambda (h) (or (plist-get h :rain) 0)) hours)))
      
      (when valid-hours
        `(:max-temp ,(apply #'max temps)
          :min-temp ,(apply #'min temps)
          :avg-pop ,(/ (apply #'+ pops) (length pops))
          :total-rain ,(apply #'+ rains)
          :hours ,(length valid-hours))))))

;;; ======================
;;; Enhanced API callback
;;; ======================

(defun weather-api-callback (status city)
  "Callback function for API responses"
  (let ((data-buffer (current-buffer)))
    (unwind-protect
        (cond
         ((eq (car status) :error)
          (let ((error-msg (format "%s: %s" city (cdr status))))
            (push error-msg weather-error-messages)
            (message "获取 %s 天气失败: %s" city (cdr status))))
         
         (t
          (goto-char (point-min))
          (if (re-search-forward "\r?\n\r?\n" nil t)
              (let* ((json-str (buffer-substring (point) (point-max)))
                     (data (ignore-errors (json-read-from-string json-str))))
                (if data
                    (if (alist-get 'list data)
                        (weather-process-data city data)
                      (push (format "%s: API响应无效 - %s" city 
                                   (or (alist-get 'message data) "未知错误")) 
                           weather-error-messages))
                  (push (format "%s: JSON解析失败" city) weather-error-messages)))
            (push (format "%s: 无效的API响应" city) weather-error-messages)))))
      
      (when (buffer-live-p data-buffer)
        (kill-buffer data-buffer)))
    
    (cl-decf weather-active-requests)
    (when (<= weather-active-requests 0)
      (weather-render-report))))

;;; ======================
;;; Enhanced rendering functions
;;; ======================

(defun weather-render-report ()
  "Render the complete weather report"
  (let ((buffer (get-buffer-create weather-buffer-name))
        (inhibit-read-only t))
    
    (with-current-buffer buffer
      (erase-buffer)
      (setq buffer-file-coding-system 'utf-8)
      
      (weather--render-header)
      
      (when weather-error-messages
        (weather--render-errors))
      
      (when (> (hash-table-count weather-city-data) 0)
        (weather--render-summary)
        (maphash (lambda (city _) (weather--render-city-detail city)) 
                 weather-city-data))
      
      (weather--render-footer)
      
      (setq buffer-read-only t)
      (org-mode)
      ;;mrsilver
    

  (org-table-map-tables (lambda () (org-table-align)) t)
      (goto-char (point-min)))
    
    (display-buffer buffer)))

(defun weather--render-header ()
  "Render report header"
  (insert "#+TITLE: 多城市天气监控\n")
  (insert "#+AUTHOR: 天气系统\n")
  (insert (format "#+DATE: %s\n\n" (format-time-string "%Y年%m月%d日 %H:%M")))
  (insert (format "**监控城市**: %s\n\n" (string-join weather-cities "、"))))

(defun weather--render-errors ()
  "Render error messages"
  (insert "**❌ 错误信息**\n")
  (dolist (err weather-error-messages)
    (insert (format "- %s\n" err)))
  (insert "\n")
  (setq weather-error-messages nil))

(defun weather--render-summary ()
  "Render daily summary table"
  (insert "**📊 每日天气摘要**\n\n")
  
  (let ((all-dates (weather--get-all-dates)))
    (dolist (date (cl-subseq all-dates 0 (min 5 (length all-dates))))
      (insert (format "*** %s (%s)\n" date (weather--get-day-name date)))
      (insert "| 城市 | 最高温 | 最低温 | 平均降雨概率 | 总降雨量 | 天气状况 |\n")
      (insert "|------|--------|--------|--------------|----------|----------|\n")
      
      (dolist (city weather-cities)
        (let* ((city-data (gethash city weather-city-data))
               (hours (when (and city-data (plist-get city-data :daily))
                       (gethash date (plist-get city-data :daily)))))
          (if hours
              (let ((stats (weather--calculate-daily-stats hours))
                    (icon (plist-get (car hours) :icon)))
                (insert (format "| %s | %.1f°C | %.1f°C | %d%% | %.1fmm | %s |\n"
                               city
                               (or (plist-get stats :max-temp) 0)
                               (or (plist-get stats :min-temp) 0)
                               (round (* (or (plist-get stats :avg-pop) 0) 100))
                               (or (plist-get stats :total-rain) 0)
                               (or icon "N/A"))))
            (insert (format "| %s | - | - | - | - | 无数据 |\n" city)))))
      (insert "\n"))))

(defun weather--render-city-detail (city)
  "Render detailed forecast for a specific city"
  (let ((city-data (gethash city weather-city-data)))
    (when city-data
      (insert (format "**🌤️ %s 详细天气预报**\n" city))
      (insert (format "最后更新: %s\n\n" 
                     (weather--format-time (float-time (plist-get city-data :last-update)))))
      
      (let ((daily-data (plist-get city-data :daily))
            (rain-periods '()))
        (when (hash-table-p daily-data)
          (maphash 
           (lambda (date hours)
             (insert (format "*** %s (%s)\n" date (weather--get-day-name date)))
             (insert "| 时间 | 温度 | 体感 | 天气 | 降雨概率 | 降雨量 | 风速 |\n")
             (insert "|------|------|------|------|----------|--------|------|\n")
             
             (dolist (hour (cl-sort hours #'< :key (lambda (h) (or (plist-get h :dt) 0))))
               (let* ((pop-percent (round (* (or (plist-get hour :pop) 0) 100)))
                      (rain-highlight (>= pop-percent rain-threshold))
                      (time (weather--format-time (plist-get hour :dt) "%H:%M")))
                 
                 (when rain-highlight
                   (push (list city date time pop-percent) rain-periods))
                 
                 (insert (format "| %s | %s | %s | %s | %s | %.1fmm | %.1fm/s |\n"
                               (or time "N/A")
                               (or (weather--format-temperature (plist-get hour :temp)) "N/A")
                               (or (weather--format-temperature (plist-get hour :feels_like)) "N/A")
                               (or (plist-get hour :description) "N/A")
                               (or (weather--format-pop pop-percent rain-highlight) "N/A")
                               (or (plist-get hour :rain) 0)
                               (or (plist-get hour :wind_speed) 0)))))
             (insert "\n"))
           daily-data))
        
        (when rain-periods
          (weather--render-rain-alerts (nreverse rain-periods)))))))

(defun weather--render-rain-alerts (periods)
  "Render rain alerts section"
  (insert "**⚠️ 降雨警报**\n")
  (insert (format "以下时间段降雨概率超过 %d%%：\n\n" rain-threshold))
  
  (let ((current-city nil)
        (current-date nil))
    (dolist (period periods)
      (let ((city (nth 0 period))
            (date (nth 1 period))
            (time (nth 2 period))
            (pop (nth 3 period)))
        
        (unless (equal city current-city)
          (insert (format "*** %s\n" city))
          (setq current-city city
                current-date nil))
        
        (unless (equal date current-date)
          (insert (format "**** %s\n" date))
          (setq current-date date))
        
        (insert (format "- %s: %d%% 降雨概率\n" time pop))))))

(defun weather--render-footer ()
  "Render footer with action buttons"
  (insert "---\n")
  (insert "**操作**\n\n")
  (insert (propertize "[[elisp:(weather-update)][🔄 立即更新]]" 
                     'face '(:box (:line-width 1 :color "blue") 
                            :background "light cyan")
                     'mouse-face 'highlight
                     'help-echo "点击手动刷新天气数据"))
  (insert "  ")
  (insert (propertize "[[elisp:(weather-set-cities)][✏️ 修改城市]]" 
                     'face '(:box (:line-width 1 :color "green") 
                            :background "honeydew")
                     'mouse-face 'highlight
                     'help-echo "点击修改监控城市列表"))
  (insert "  ")
  (insert (propertize "[[elisp:(weather-customize)][⚙️ 设置]]" 
                     'face '(:box (:line-width 1 :color "orange") 
                            :background "seashell")
                     'mouse-face 'highlight
                     'help-echo "点击进行系统设置"))
  (insert "\n\n"))

;;; ======================
;;; Additional utility functions
;;; ======================

(defun weather--get-day-name (date)
  "Get day name from date string"
  (let ((time (date-to-time (concat date " 00:00:00"))))
    (format-time-string "%A" time)))

;;; ======================
;;; User interaction functions
;;; ======================

(defun weather-update (&optional interactive)
  "Manual weather update function"
  (interactive "p")
  (setq weather-error-messages nil)
  (clrhash weather-city-data)
  (setq weather-active-requests 0)
  
  (dolist (city weather-cities)
    (weather-start-request city))
  
  (when interactive
    (message "开始更新天气数据...")))

(defun weather-set-cities ()
  "Function to set monitored cities"
  (interactive)
  (let ((new-cities (split-string 
                    (read-string "输入城市列表(逗号分隔): " 
                                (string-join weather-cities ", "))
                    ",\\s-*")))
    (when new-cities
      (setq weather-cities new-cities)
      (weather-update t))))

(defun weather-customize ()
  "Function to customize weather settings"
  (interactive)
  (customize-group 'weather))

(defun weather-auto-update ()
  "Function to enable automatic weather updates"
  (interactive)
  (cancel-function-timers 'weather-update)
  (run-with-timer 0 weather-refresh-interval 'weather-update)
  (message "天气自动更新已启用 (每 %d 秒)" weather-refresh-interval))

;; Fixed initialization function
(defun weather-init ()
  "Initialize weather system"
  (interactive)
  (weather-check-api-key)
  (weather-auto-update)
  (weather-update t)
  (message "天气系统初始化完成"))

(provide 'weather)
